version: '3.8'

services:
  # Laravel application service (PHP-FPM)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www  # Mount the current directory into the container
    expose:
      - "9000"  # Expose PHP-FPM port to other services (Nginx)
    networks:
      - laravel
    depends_on:
      - sqlite

  # SQLite Database (using a volume for the database file)
  sqlite:
    image: alpine/sqlite
    container_name: sqlite_db
    volumes:
      - ./database:/var/db  # SQLite database file is stored here
    networks:
      - laravel
    environment:
      - SQLITE_DATABASE=/var/db/database.sqlite

  # Nginx service (used to serve the Laravel app via HTTP)
  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount custom Nginx config
    ports:
      - "8080:8080"  # Expose port 80 to the host
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
